# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0002_auto_20170912_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='validation_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='potential_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
