# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0003_auto_20170917_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.ManyToManyField(blank=True, to='kuriocities.City'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='context',
            field=models.ManyToManyField(blank=True, to='kuriocities.Context'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Cost'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='curriculum',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Official Curriculum'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dates_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Duration'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='first_session',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='job',
            field=models.ManyToManyField(blank=True, to='kuriocities.Job'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='last_session',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ManyToManyField(blank=True, to='kuriocities.Location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Situation'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='skill',
            field=models.ManyToManyField(blank=True, to='kuriocities.Skill'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sponsored',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.ManyToManyField(blank=True, to='kuriocities.Subject'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='times_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='validation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.ValidationType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.AgeGroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Curriculum'),
        ),
        migrations.AlterField(
            model_name='question',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Execution'),
        ),
        migrations.AlterField(
            model_name='question',
            name='job',
            field=models.ManyToManyField(blank=True, to='kuriocities.Job'),
        ),
        migrations.AlterField(
            model_name='question',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='potential_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='sequence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.SequenceType'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.ManyToManyField(blank=True, to='kuriocities.Skill'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ManyToManyField(blank=True, to='kuriocities.Subject'),
        ),
    ]
