# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0004_auto_20170918_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='permanent_dates',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
