# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0013_auto_20170921_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
