# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0014_useractivity_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.UserActivityState'),
        ),
    ]
