# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0015_auto_20170922_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ('user', 'activity')},
        ),
    ]
