# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0016_auto_20170922_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(blank=True, default=999)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityquestion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='activityquestion',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityquestion',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='activityquestion',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ('user', 'activity'), 'verbose_name_plural': 'User activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='job',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sequence_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='age_group',
            field=models.ManyToManyField(blank=True, to='kuriocities.AgeGroup'),
        ),
        migrations.AddField(
            model_name='activity',
            name='previous_Activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sequence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.SequenceType'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_answer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='objectives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.LearningObjectives'),
        ),
        migrations.DeleteModel(
            name='ActivityQuestion',
        ),
    ]
