# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0018_auto_20170923_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityquestion',
            options={'ordering': ('activity', 'age_group', 'question_no')},
        ),
    ]
