# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0019_auto_20170923_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='age_group',
        ),
    ]
