# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0023_auto_20170924_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningObjectives',
            new_name='LearningObjective',
        ),
    ]
