# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0024_auto_20170924_0118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityquestion',
            unique_together=set([('activity', 'age_group', 'question'), ('activity', 'age_group', 'question_no')]),
        ),
    ]
