# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0026_auto_20170924_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
