# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0027_location_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='question',
            name='age_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.AgeGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='location',
            name='created',
        ),
        migrations.RemoveField(
            model_name='location',
            name='modified',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('city', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('age_group', 'question')]),
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='modified',
        ),
        migrations.AlterUniqueTogether(
            name='questiontype',
            unique_together=set([('validation_type', 'name')]),
        ),
    ]
