# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0031_auto_20171014_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='first_session',
            new_name='from_time',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='last_session',
            new_name='to_time',
        ),
    ]
