# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0032_auto_20171016_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hours_24',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
