# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0033_activity_hours_24'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avatar_bullet_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='avatar_bullet_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='guide_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
