# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0034_auto_20171016_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age_groups',
            field=models.ManyToManyField(blank=True, to='kuriocities.AgeGroup'),
        ),
    ]
