# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0035_activity_age_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='guide_description',
        ),
    ]
