# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0036_remove_activity_guide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Execution'),
        ),
        migrations.AddField(
            model_name='activity',
            name='translatabilityAreas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='translatable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
