# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0037_auto_20171017_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Activity')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuriocities.LearningOutcomeVerb')),
            ],
            options={
                'ordering': ('activity', 'verb'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='activitycontext',
            unique_together=set([('activity', 'verb')]),
        ),
    ]
