# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0038_auto_20171017_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityContext',
            new_name='ActivityOutcome',
        ),
    ]
