# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0040_auto_20171017_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityoutcome',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuriocities.Activity'),
        ),
        migrations.AlterField(
            model_name='activityoutcome',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuriocities.LearningOutcomeVerb'),
        ),
    ]
