# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0042_auto_20171018_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='age_group',
        ),
    ]
