# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0043_remove_question_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('feedback', models.TextField()),
                ('order', models.IntegerField(blank=True, default=999)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuriocities.Question')),
            ],
            options={
                'ordering': ('question', 'order', 'pk'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='questionchoice',
            unique_together=set([('question', 'choice')]),
        ),
    ]
