# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0044_auto_20171018_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='duration',
            options={'ordering': ['order', 'id']},
        ),
    ]
