# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 11:04
from __future__ import unicode_literals

from django.db import migrations


def create_activity_statuses( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'ActivityStatus' )
    for order, status in enumerate([ 'Draft', 'Published' ]):
        model.objects.get_or_create(
            name = status,
            defaults = {
                'order': order,
            }
        )


def default_activity_status( apps, schema_editor ):
    model  = apps.get_model( 'kuriocities', 'Activity' )
    status = apps.get_model( 'kuriocities', 'ActivityStatus' ).objects.get( name='Draft' )
    model.objects.filter( status=None ).update( status=status )


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0047_activity_status'),
    ]

    operations = [
        migrations.RunPython( create_activity_statuses, migrations.RunPython.noop ),
        migrations.RunPython( default_activity_status,  migrations.RunPython.noop ),
    ]
