# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0048_auto_20171021_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitystatus',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Activity statuses'},
        ),
        migrations.AddField(
            model_name='question',
            name='learningOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.ActivityOutcome'),
        ),
    ]
