# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0050_auto_20171021_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='validation_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='needs_coach',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
