# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 05:54
from __future__ import unicode_literals

from django.db import migrations

LEARNING_OUTCOME_CATEGORIES = (
    ( 'Comprehend',   'Comprehend'   ),
    ( 'Apply',        'Apply'        ),
    ( 'Analyze',      'Analyze'      ),
    ( 'Synthesize',   'Synthesize'   ),
    ( 'Evaluate',     'Evaluate'     ),
    ( 'Emotionalize', 'Emotionalize' ),
)


def outcome( category ):
    return {
        "category": category,
        "verb":     "",
        "text":     "",
    }

def get_outcomes( activity ):

    activityOutcomes = {
        ao.verb.category : {
            'category': ao.verb.category,
            'verb':     ao.verb.verb,
            'text':     ao.text,
        }
        for ao in activity.activityoutcome_set.all()
    }
    data = [
        activityOutcomes.get( category, outcome( category ) )
        for category, _ in LEARNING_OUTCOME_CATEGORIES
    ]
    return data


def save_activity_data( apps, schema_editor ):
    Activity = apps.get_model( 'kuriocities', 'Activity' )
    for activity in Activity.objects.all().prefetch_related():
        activity.data = {
            "id"                      : activity.id,
            "title"                   : activity.title,
            "status"                  : activity.status.name,
            "briefDescription"        : activity.brief_description,
            "description"             : activity.description,
            "previousActivity"        : activity.previous_activity.title if activity.previous_activity else '',
            "cities"                  : [ x.name for x in activity.cities.all() ],
            "locations"               : [ x.name for x in activity.locations.all() ],
            "pictureUrl"              : activity.picture_url,
            "videoUrl"                : activity.video_url,
            "duration"                : activity.duration.name  if activity.duration  else '',
            "situation"               : activity.situation.name if activity.situation else '',
            "execution"               : activity.execution.name if activity.execution else '',
            "contexts"                : [ x.name for x in activity.contexts.all() ],
            "fromDate"                : activity.from_date.strftime( '%Y-%m-%d' ) if activity.from_date else '',
            "toDate"                  : activity.to_date.strftime( '%Y-%m-%d' )   if activity.to_date   else '',
            "permanentDates"          : activity.permanent_dates,
            "datesComment"            : activity.dates_comment,
            "fromTime"                : activity.from_time.strftime( '%H:%M' ) if activity.from_time else '',
            "toTime"                  : activity.to_time.strftime( '%H:%M' )   if activity.to_time   else '',
            "hours24"                 : activity.hours_24,
            "timesComment"            : activity.times_comment,
            "cost"                    : activity.cost.name if activity.cost else '',
            "jobs"                    : [ x.name for x in activity.jobs.all() ],
            "sponsored"               : activity.sponsored,
            "needsCoach"              : activity.needs_coach,
            "avatarBullet1"           : activity.avatar_bullet_1,
            "avatarBullet2"           : activity.avatar_bullet_2,
            "ageGroups"               : [ x.name for x in activity.age_groups.all() ],
            "translatable"            : activity.translatable,
            "translatabilityAreas"    : activity.translatability_areas,
            "outcomes"                : get_outcomes( activity ),
        }
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0052_activity_data'),
    ]

    operations = [
        migrations.RunPython( save_activity_data, migrations.RunPython.noop ),
    ]
