# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:16
from __future__ import unicode_literals

from django.db import migrations

def update_username( apps, schema_editor ):
    Activity = apps.get_model ('kuriocities', 'Activity' )
    for activity in Activity.objects.all():
        activity.data['username'] = activity.created_by.username
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0055_fix_missing_data_fields'),
    ]

    operations = [
        migrations.RunPython( update_username, migrations.RunPython.noop ),
    ]
