# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0056_data_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=32)),
                ('feedback', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, default=999)),
            ],
            options={
                'ordering': ['feedback_type', 'order', 'feedback'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cannedfeedback',
            unique_together=set([('feedback_type', 'feedback')]),
        ),
    ]
