# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 15:30
from __future__ import unicode_literals

from django.db import migrations


def set_default_value( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'Activity' )
    for row in model.objects.all():
        if hasattr( row, 'data' ):
            if not row.data.get( 'coach' ):
                row.data ['coach'] = row.created_by.username
                row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0057_auto_20171028_2035'),
    ]

    operations = [
        migrations.RunPython( set_default_value, migrations.RunPython.noop )
    ]
