# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0058_default-coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Activity'),
        ),
    ]
