# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0059_auto_20171114_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Activity'),
        ),
    ]
