# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0061_auto_20171114_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_cell_no',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='interactions_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='next_steps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='tel_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
