# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kuriocities.models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0062_auto_20171118_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='state',
            field=models.ForeignKey(default=kuriocities.models.default_UserActivityState, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.UserActivityState'),
        ),
    ]
