# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0063_auto_20171129_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='actions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
