# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0065_useractivity_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='answers',
        ),
    ]
