# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:31
from __future__ import unicode_literals

from django.db import migrations

from time import time


def set_question_id( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'Activity' )
    for row in model.objects.all():
        for question in row.data.get( 'questions', [] ):
            if not question.get( 'id' ):
                question['id'] = int( time() * 1000000 )
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0067_useractivity_answers'),
    ]

    operations = [
        migrations.RunPython( set_question_id, migrations.RunPython.noop )
    ]
