# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:14
from __future__ import unicode_literals

from django.db import migrations

def set_logicalType( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'Activity' )
    for row in model.objects.all():
        for question in row.data.get('questions', []):
            if question['questionType'] == 'logic' and question['logicalType'] == 'between':
                question['logicalType'] == 'betweenExc'
                row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0068_Activity_data_questions_question_id'),
    ]

    operations = [
        migrations.RunPython( set_logicalType, migrations.RunPython.noop ),
    ]
