# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:14
from __future__ import unicode_literals

from django.db import migrations


def set_operands( apps, schema_editor ):
    fields = [ 'logicalTypeOperand1', 'logicalTypeOperand2', 'mathTypeOperand1', 'mathTypeOperand2' ]
    model = apps.get_model( 'kuriocities', 'Activity' )
    for activity in model.objects.all().order_by( 'modified' ):
        questions = activity.data.get('questions', [])
        for question in questions:
            for field in fields:
                operand = question.get( field )
                if not operand:  continue
                if operand == -1:
                    question[ field ] = -1
                    continue
                try:
                    if isinstance( operand, list ):
                        question[ field ] = [ questions[ qno ] ['id'] for qno in operand if qno ]
                    else:
                        question[ field ] = questions[ operand ] ['id']
                except:
                    print( field, operand )
                    raise
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0069_question_logicalType_between'),
    ]

    operations = [
        migrations.RunPython( set_operands, migrations.RunPython.noop ),
    ]
