# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:49
from __future__ import unicode_literals

from django.db import migrations


def set_order( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'Activity' )
    for activity in model.objects.all():
        for question in activity.data.get( 'questions', [] ):
            for i, choice in enumerate( question.get( 'choices', [] )):
                if choice['order']  == 999:
                    choice['order'] = (i + 1) * 10
        activity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0071_data_question_order'),
    ]

    operations = [
        migrations.RunPython( set_order, migrations.RunPython.noop ),
    ]
