# Generated by Django 2.0 on 2017-12-18 16:05

from django.db  import migrations

def migrate_skills( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'Activity' )
    for activity in model.objects.all():
        for question in activity.data.get( 'questions', [] ):
            question['subjects'] = []
            if 'subject' in question:
                question['subjects'].append( question['subject'] )
                del question['subject']
        activity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0074_auto_20171215_1536'),
    ]

    operations = [
        migrations.RunPython( migrate_skills, migrations.RunPython.noop ),
    ]
