# Generated by Django 2.0 on 2017-12-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0075_data_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='completedQuestion',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
