# Generated by Django 2.0 on 2017-12-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0076_useractivity_completedquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='completedQuestion',
            new_name='completed_question',
        ),
    ]
