# Generated by Django 2.0 on 2018-01-12 12:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0077_auto_20171226_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='uploads',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
