# Generated by Django 2.0 on 2018-01-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0078_useractivity_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attempt_no', models.IntegerField(blank=True, default=1)),
                ('points', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'ordering': ['answer_point_type', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='AnswerPointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(blank=True, default=999)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answerpoint',
            name='answer_point_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuriocities.AnswerPointType'),
        ),
        migrations.AlterUniqueTogether(
            name='answerpoint',
            unique_together={('answer_point_type', 'attempt_no')},
        ),
    ]
