# Generated by Django 2.0 on 2018-01-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0079_auto_20180114_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpoint',
            name='attempt_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answerpoint',
            name='points',
            field=models.IntegerField(),
        ),
    ]
