# Generated by Django 2.0 on 2018-01-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0080_auto_20180114_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerPoint',
            new_name='AnswerScore',
        ),
        migrations.RenameModel(
            old_name='AnswerPointType',
            new_name='AnswerScoreType',
        ),
        migrations.AlterModelOptions(
            name='answerscore',
            options={'ordering': ['answer_score_type', 'attempt_no']},
        ),
        migrations.RenameField(
            model_name='answerscore',
            old_name='answer_point_type',
            new_name='answer_score_type',
        ),
        migrations.AlterUniqueTogether(
            name='answerscore',
            unique_together={('answer_score_type', 'attempt_no')},
        ),
    ]
