# Generated by Django 2.0 on 2018-01-15 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0081_auto_20180115_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='answer_attemps',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
