# Generated by Django 2.0 on 2018-01-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0083_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='answer_attemps',
            new_name='answer_attempts',
        ),
    ]
