# Generated by Django 2.0 on 2018-01-16 14:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0087_auto_20180116_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
