# Generated by Django 2.0 on 2018-02-08 02:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kuriocities', '0091_capitalize-verbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('invitees', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Activity')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inviter', 'created', 'activity'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('created', 'inviter', 'activity')},
        ),
    ]
