# Generated by Django 2.0.2 on 2018-02-13 12:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kuriocities', '0093_useractivity_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('completed_question', models.IntegerField(blank=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('answer_attempts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('uploads', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('actions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('archive_date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Activity')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Invitation')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kuriocities.UserActivityState')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
