# Generated by Django 2.0.2 on 2018-02-16 13:15

from django.db import migrations

from pdb import set_trace as st


def change_user( activity ):
    if activity.data.get( 'coach' ) == 'olivia.tay@edunexis.com':
        activity.data ['coach'] = 'ricard.gras@edunexis.com'

    if activity.data.get( 'checker' ) == 'olivia.tay@edunexis.com':
        activity.data ['checker'] = 'ricard.gras@edunexis.com'

    return activity


def set_checker( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'Activity' )
    User  = apps.get_model( 'auth', 'User' )
    for activity in model.objects.order_by( 'modified' ):
        activity = change_user( activity )

        if any( question.get( 'needsChecker' ) for question in activity.data ['questions'] ):
            checker = (
                activity.data ['coach'] if   activity.data.get( 'needsCoach' ) and activity.data.get( 'coach' )
                else activity.data ['checker'] if activity.data.get( 'checker' )
                else None
            )
            checker = User.objects.get( username = checker ) if checker else activity.created_by
            activity.checker = checker
            activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0095_activity_checker'),
    ]

    operations = [
        migrations.RunPython( set_checker, migrations.RunPython.noop ),
    ]
