# Generated by Django 2.0.2 on 2018-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0096_set_activity_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
