# Generated by Django 2.0.2 on 2018-02-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0097_invitation_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='completed_date',
        ),
    ]
