# Generated by Django 2.0.2 on 2018-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0098_remove_invitation_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
