# Generated by Django 2.0.2 on 2018-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0099_auto_20180217_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_checked',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='invitation',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
