# Generated by Django 2.0.2 on 2018-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0100_auto_20180217_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
