# Generated by Django 2.0.2 on 2018-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0101_useractivity_date_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerScoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(blank=True, default=999)),
                ('min_score', models.IntegerField()),
                ('m_score', models.IntegerField()),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useractivityarchive',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
