# Generated by Django 2.0.2 on 2018-03-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0102_auto_20180301_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkerscoretype',
            old_name='m_score',
            new_name='max_score',
        ),
    ]
