# Generated by Django 2.0.2 on 2018-03-01 05:29

from django.db import migrations, models
import django.db.models.deletion
import kuriocities.models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0103_auto_20180301_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivityarchive',
            name='completed_question',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='useractivityarchive',
            name='invitation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Invitation'),
        ),
        migrations.AlterField(
            model_name='useractivityarchive',
            name='state',
            field=models.ForeignKey(default=kuriocities.models.default_UserActivityState, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.UserActivityState'),
        ),
    ]
