# Generated by Django 2.0.2 on 2018-03-01 16:12

from django.db import migrations

def convert_scores( apps, schema_editor ):

    model = apps.get_model( 'kuriocities', 'UserActivity' )
    for x in model.objects.all():
        scores = x.scores.get( 'questions' )
        if not scores: continue
        if not isinstance( scores, list ): continue
        x.scores ['questions'] = { str(i): item for i, item in enumerate(scores) }
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0105_scores-questions'),
    ]

    operations = [
        migrations.RunPython( convert_scores, migrations.RunPython.noop ),
    ]
