# Generated by Django 2.0.2 on 2018-03-02 03:54

from django.db import migrations

def upload_scores( apps, schema_editor ):
    count = 0
    model = apps.get_model( 'kuriocities', 'UserActivity' )
    for ua in model.objects.all():
        questions = ua.activity.data.get( 'questions' ) or []
        for idx, question in enumerate( questions ):
            if question.get( 'questionType' ) == 'upload':
                scores = ua.scores.get( 'questions' )
                if not scores: continue
                count += 1
                scores [idx] = [0, 0]
                ua.save()
    print( '%s rows affected' % count )

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0107_clean-checker-scores'),
    ]

    operations = [
        migrations.RunPython( upload_scores, migrations.RunPython.noop ),
    ]
