# Generated by Django 2.0.2 on 2018-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0108_upload-scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='date_commented',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivityarchive',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivityarchive',
            name='date_commented',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date completed'),
        ),
        migrations.AlterField(
            model_name='useractivityarchive',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date completed'),
        ),
    ]
