# Generated by Django 2.0.2 on 2018-03-07 06:29

from django.db import migrations


def create_group( apps, schema_editor ):
    model = apps.get_model( 'auth', 'Group' )
    model.objects.get_or_create( name='KCT-Reviewer' )

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0109_auto_20180306_1737'),
    ]

    operations = [
        migrations.RunPython( create_group, migrations.RunPython.noop ),
    ]
