# Generated by Django 2.0.2 on 2018-03-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0111_userprofile_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
