# Generated by Django 2.0.2 on 2018-03-19 08:46

from django.db import migrations


def init_introUrlType( apps, schema_editor ):
    model = apps.get_model( 'kuriocities', 'Activity' )
    for activity in model.objects.order_by( 'modified' ):
        dirty = False
        if activity.data.get( 'introUrl' ):
            activity.data ['introUrlType'] = 'urlPicture'
            dirty = True
        if activity.data.get( 'pictureUrl' ):
            activity.data ['pictureUrlType'] = 'urlPicture'
            dirty = True
        for question in activity.data.get( 'questions', [] ):
            if question.get( 'pictureUrl' ):
                question ['pictureUrlType'] = 'urlPicture'
                dirty = True
        if dirty:
            activity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0112_invitation_start_date'),
    ]

    operations = [
        migrations.RunPython( init_introUrlType, migrations.RunPython.noop ),
    ]
