# Generated by Django 2.0.2 on 2018-04-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0113_init_activity_intro_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useractivityarchive',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
