# Generated by Django 2.0.3 on 2018-05-26 11:48

from django.db import migrations

def add_groups( apps, schema_editor ) -> None:
    groups = [
        'KCT-Activity-Data',
    ]
    model = apps.get_model( 'auth', 'Group' )
    for group in groups:
        model.objects.get_or_create( name=group )


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0115_add_groups'),
    ]

    operations = [
        migrations.RunPython( add_groups, migrations.RunPython.noop ),
    ]
