# Generated by Django 2.0.6 on 2018-06-26 01:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0118_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivityjournal',
            name='uploads',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
