# Generated by Django 2.0.7 on 2018-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0120_auto_20180706_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('invitation', 'time', 'user')},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='team',
            field=models.CharField(default='', max_length=32),
        ),
    ]
