# Generated by Django 2.0.7 on 2018-08-10 14:29

from django.db import migrations


def add_group( apps, schema_editor ):
    model = apps.get_model( 'auth', 'Group' )
    model.objects.get_or_create( name='KCT-Messaging' )


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0121_auto_20180719_1419'),
    ]

    operations = [
        migrations.RunPython( add_group, migrations.RunPython.noop ),
    ]
