# Generated by Django 2.0.7 on 2018-08-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0123_learningjournal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningjournal',
            old_name='texttitle',
            new_name='title',
        ),
    ]
