# Generated by Django 2.0.7 on 2018-08-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0124_auto_20180820_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivityjournal',
            name='user_activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kuriocities.UserActivity'),
        ),
    ]
