# Generated by Django 2.0.7 on 2018-09-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0127_auto_20180909_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitytodo',
            name='message',
        ),
    ]
