# Generated by Django 2.0.7 on 2018-09-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0128_remove_useractivitytodo_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivityjournal',
            options={'ordering': ('user_activity',)},
        ),
        migrations.RenameField(
            model_name='useractivityjournal',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='useractivityjournal',
            name='uploads',
        ),
    ]
