# Generated by Django 2.0.7 on 2018-10-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0130_auto_20181008_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent__name', 'name'), 'verbose_name_plural': 'Categories'},
        ),
    ]
