# Generated by Django 2.0.7 on 2018-10-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0134_AppFeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
