# Generated by Django 2.0.7 on 2018-11-01 13:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0135_category_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='action_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivitytodo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.Category'),
        ),
        migrations.AddField(
            model_name='useractivitytodo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitees',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='learningjournal',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='useractivitytodo',
            name='user_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuriocities.UserActivity'),
        ),
    ]
