# Generated by Django 2.0.7 on 2018-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuriocities', '0136_auto_20181101_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitytodo',
            name='question_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
